[package]
name = "wasm-interface-types"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
wast = "3.0"

[workspace]
members = [
  'crates/text',
  'crates/parser',
]

[patch.crates-io]
wast = { path = '../wat/crates/wast' }
