[package]
name = "wit-printer"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
wasmprinter = "0.2"
wit-parser = { path = "../parser" }

[dev-dependencies]
getopts = "0.2"
wit-validator = { path = "../validator" }
