[package]
name = "test-helpers"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[lib]
test = false
doctest = false

[dependencies]
anyhow = "1.0"
rayon = "1.0"
