[package]
name = "wit"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
wast = "3.0"
anyhow = "1.0"

[dev-dependencies]
rayon = "1.0"

[[test]]
name = "parse-fail"
harness = false
