[package]
name = "wit-text"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
leb128 = "0.2"
wast = { git = 'https://github.com/bytecodealliance/wat' }
wit-schema-version = { path = "../schema-version" }

[dev-dependencies]
getopts = "0.2"
test-helpers = { path = "../test-helpers" }
wasmparser = "0.42"
wat = "1.0"
wit-parser = { path = "../parser" }
wit-printer = { path = "../printer" }
wit-validator = { path = "../validator" }

[[test]]
name = "all"
harness = false
