[package]
name = "wit-text"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
wast = { git = 'https://github.com/bytecodealliance/wat' }
anyhow = "1.0"
leb128 = "0.2"
wit-schema-version = { path = "../schema-version" }

[dev-dependencies]
test-helpers = { path = "../test-helpers" }
wasmparser = "0.39"
wit-parser = { path = "../parser" }

[[test]]
name = "parse-fail"
harness = false

[[test]]
name = "parse-pass"
harness = false
